services:
    ticketpark.file.handler:
        class: 'Ticketpark\FileBundle\FileHandler\FileHandler'
        arguments: ['@buzz', '%kernel.cache_dir%/files/']

    ticketpark.file.encoder:
        class: 'Ticketpark\FileBundle\FileEncoder\FileEncoder'
        arguments: ['@ticketpark.file.handler']

    ticketpark.file.twig_encoder_extension:
        class: 'Ticketpark\FileBundle\Twig\FileEncoderExtension'
        arguments: ['@ticketpark.file.encoder']
        tags:
            - { name: twig.extension }