parameters:
    ticketpark.file.handler.class:          Ticketpark\FileBundle\FileHandler\FileHandler
    ticketpark.file.encoder.class:          Ticketpark\FileBundle\FileEncoder\FileEncoder
    ticketpark.file.twig_extension.class:   Ticketpark\FileBundle\Twig\FileExtension

services:
    ticketpark.file.handler:
        class: %ticketpark.file.handler.class%
        arguments: [@buzz, '%kernel.cache_dir%/files/']

    ticketpark.file.encoder:
        class: %ticketpark.file.encoder.class%
        arguments: [@ticketpark.file.handler]

    ticketpark.file.twig_extension:
        class: %ticketpark.file.twig_extension.class%
        arguments: [@ticketpark.file.encoder]
        tags:
            - { name: twig.extension }
